# Generated by Django 4.1.3 on 2022-11-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="is_anonymous",
            field=models.BooleanField(
                default=False,
                help_text="Choose whether the chatroom should be anonymous",
            ),
        ),
    ]
