# Generated by Django 4.1.3 on 2022-11-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0002_chatroom_is_anonymous"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="is_anonymous",
            field=models.BooleanField(
                default=True,
                help_text="Choose whether the chatroom should be anonymous",
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="summary",
            field=models.TextField(
                help_text="Enter summary of the chatroom", max_length=1000, null=True
            ),
        ),
    ]
