# Generated by Django 4.1.3 on 2022-11-10 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatroom", "0003_alter_chatroom_is_anonymous_alter_chatroom_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="createc_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
