# Generated by Django 4.1.3 on 2022-11-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0004_message_createc_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="is_anonymous",
            field=models.BooleanField(
                help_text="Choose whether the chatroom should be anonymous"
            ),
        ),
    ]
